headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\pedro.alves\\.gemini\\antigravity-ide\\HEATING COOLING"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/app.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/service-worker.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Content-Type = "application/manifest+json; charset=utf-8"